version: '2'
services:

  postgresql:
    build:
      context: postgresql
      dockerfile: Dockerfile
    container_name: postgresql
    restart: always
    volumes:
      - /home/namayeyar/data/postgresql:/var/lib/postgresql/data
      - ./postgresql/init_script.sh:/docker-entrypoint-initdb.d/init_script.sh
    environment:
      - POSTGRES_PASSWORD
      - NAMAYEYAR_DB
      - NAMAYEYAR_DB_USER
      - NAMAYEYAR_DB_PASS

  rabbitmq:
    image: rabbitmq:3.6.0
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS

  ner:
    build:
      context: namayeyar-ner
      dockerfile: Dockerfile
      args:
        - proxy=http://nol-dt01:noldt@172.16.25.19:8000
    container_name: ner
    restart: always
    command: /app/run_ner.sh
    volumes:
      - ./namayeyar-ner:/app
    environment:
      - PYTHONIOENCODING
      # - http_proxy
      # - https_proxy

  namayeyar:
    build:
      context: namayeyar
      dockerfile: Dockerfile
      args:
      - proxy=http://nol-dt01:noldt@172.16.25.19:8000
    container_name: namayeyar
    restart: always
    command: /app/run_namayeyar.sh
    environment:
      # - http_proxy
      # - https_proxy
      - PYTHONIOENCODING
      - NER_API
      - WEB_DEBUG=False
      - NAMAYEYAR_DB
      - NAMAYEYAR_DB_USER
      - NAMAYEYAR_DB_PASS
      - DB_HOST=postgresql
      - DB_PORT=5432
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - RABBITMQ_HOST_NAME=rabbitmq
      - OUTPUT_FILES_DIR=/app/output_files
      - NAMAYEYAR_EMAIL_USER
      - NAMAYEYAR_EMAIL_PASSWORD
    depends_on:
      - postgresql
      - rabbitmq
      - ner
    volumes:
      - ./namayeyar:/app
    ports:
      - "127.0.0.1:8005:80"
